nome=input('qual seu nome?')
dia=input ('Qual dia do seu nascimento')
mês=input('qual mês do seu nascimento')
ano=input('qual ano do seu nascimento')
print(nome,'esse é o nome da pessoa mais linda desse mundo')
print('princesa', nome)
print(dia,mês,ano)
print('que coincidencia foi nessa data que o amor da vida do meu criador nasceu')
pergunta1=input('por acaso seu nome séria giovana campos chagas?')
print('eitaaa')

pergunta2=input('Você é ela mesmo a famosa?')
print('muito prazer,princesa gigi,você é a maior celebridade por aqui')
pergunta3=input('Você sabia que meu criador te ama muito?')
print('pois é,não parece mas ele  te ama muito')
pergunta4=input('Você sabia que meu criador quer casar com vc?')
print('sério mesmo? hahaha,acho que acabei de explanar um segredo dele,isso é um segredo nosso agora :)')
pergunta5=input('meu criador tá perguntando que se vc ama ele?')
print('ele vai ficar muito feliz em saber,gigi é um prazer conversar com Você,alguem tão importante para o homem que me criou')
pergunta6=input('meu criador te fez mal hoje?')
print('ele é complicado as vezes mesmo hmm...')
print('Meu criador disse que quer muito te pedir desculpas')
pergunta7=input('Você perdoa ele?')
print('Ele botou todo cérebro dele pra fazer esse presente pra Você,Cérebro esse que ele tem pouco,perdoa ele vai')
print('Por isso as vezes ele fala e faz besteiras')
pergunta8=input('Você acha que homem pensa?')
print('Não né amiga')
pergunta9=input('Você perdoa esse idiota amiga?')
print('perdoa vai')
pergunta10=input('vai pelo menos pensar?')
print('ebaa!!,adorei conversar com vc gigi')
pergunta11=input('você pode me dar um nome?,ele disse que fui feita pra você')
print('é um lindo nome,muito obrigada')
print ('tchau gigi,obrigada por aturar meu criador,ele te ama muito mesmo sendo um bobo as vezes,quase sempre ;)')